### ISSUE TITLE
Request for Access to Weather-KITTI and Weather-NuScenes Datasets

### ISSUE THREAD

**Issue by Naclzno** [Grandzxw/TripleMixer#2]
First, thank you for your invaluable contribution to the research community. Your work is truly remarkable and inspiring. I would like to kindly request access to the Weather-KITTI and Weather-NuScenes datasets that you introduced in your publication. Could you please provide information on how to obtain these datasets?

**Comment by Grandzxw** [comment]
> > Thank you for your attention, we will release it as soon as possible within two weeks.
> 
> HI

BaiduPan for Chinese mainland dataset download link has been updated!
