### ISSUE TITLE
How to Access to Weather-KITTI and Weather-NuScenes Datasets 

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [Grandzxw/TripleMixer#3]
Excuse me. 
Thank you for your outstanding work. I want to ask how I can access the datasets (both weather-kitti and weather-nuscenes) you have published.

**Comment by Grandzxw** [comment]
> Excuse me. Thank you for your outstanding work. I want to ask how I can access the datasets (both weather-kitti and weather-nuscenes) you have published.

BaiduPan for Chinese mainland dataset download link has been updated!
